'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';

import GlobalStyles from '@/styles/GlobalStyles';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'UyeonHome',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <GlobalStyles />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
